---

- name: "5.6.1.1 | PATCH | Ensure password expiration is 365 days or less"
  block:
      - name: "5.6.1.1 | AUDIT | Ensure password expiration is 365 days or less | Capture accounts more than 365"
        ansible.builtin.shell: "grep -E '^[^:]+:[^!*]' /etc/shadow | awk -F':' '$5>{{ rhel8cis_pass['max_days'] }} { print $1 }'"
        changed_when: false
        failed_when: rhel8cis_5_6_1_1_pass_max_expire.rc not in [ 0, 1 ]
        register: rhel8cis_5_6_1_1_pass_max_expire

      - name: "5.6.1.1 | PATCH | Ensure password expiration is 365 days or less | update login.defs"
        ansible.builtin.lineinfile:
            path: /etc/login.defs
            regexp: '^PASS_MAX_DAYS'
            line: "PASS_MAX_DAYS {{ rhel8cis_pass['max_days'] }}"

      - name: "5.6.1.1 | PATCH | Ensure password expiration is 365 days or less | Ensure all accounts set to 365"
        ansible.builtin.user:
            name: "{{ item }}"
            password_expire_max: "{{ rhel8cis_pass['max_days'] }}"
        loop: "{{ rhel8cis_5_6_1_1_pass_max_expire.stdout_lines | default([]) }}"
        when:
            - rhel8cis_5_6_1_1_set_max_expiry
            - item not in rhel8cis_5_6_1_1_user_skip_list

      - name: "5.6.1.1 | PATCH | Ensure password expiration is 365 days or less | Warning"
        block:
            - name: "5.6.1.1 | PATCH | Ensure password expiration is 365 days or less | Output list if not set to change"
              ansible.builtin.debug:
                  msg: |
                    "Warning!! The following account are set beyond the expected expiration date:
                     {{ rhel8cis_5_6_1_1_set_max_expiry.stdout_lines }}"

            - name: "5.6.1.1 | PATCH | Ensure password expiration is 365 days or less | set warning fact"
              ansible.builtin.import_tasks: warning_facts.yml
              vars:
                  warn_control_id: '5.6.1.1'
        when:
            - rhel8cis_5_6_1_1_pass_max_expire is defined
            - rhel8cis_5_6_1_1_pass_max_expire.stdout | length > 0
            - not rhel8cis_5_6_1_1_set_max_expiry
  when:
      - rhel8cis_rule_5_6_1_1
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - password
      - rule_5.6.1.1

- name: "5.6.1.2 | PATCH | Ensure minimum days between password changes is 7 or more"
  block:
      - name: "5.6.1.2 | AUDIT | Ensure minimum days between password changes is 7 or more | Capture accounts 7 or more"
        ansible.builtin.shell: "grep -E '^[^:]+:[^!*]' /etc/shadow | awk -F':' '$4>{{ rhel8cis_pass['min_days'] }} { print $1 }'"
        changed_when: false
        failed_when: rhel8cis_5_6_1_2_min_day_change.rc not in [ 0, 1 ]
        register: rhel8cis_5_6_1_2_min_day_change

      - name: "5.6.1.2 | PATCH | Ensure minimum days between password changes is 7 or more"
        ansible.builtin.lineinfile:
            path: /etc/login.defs
            regexp: '^PASS_MIN_DAYS'
            line: "PASS_MIN_DAYS {{ rhel8cis_pass['min_days'] }}"

      - name: "5.6.1.2 | PATCH | Ensure minimum days between password changes is 7 or more | Change users found"
        ansible.builtin.user:
            name: "{{ item }}"
            password_expire_min: "{{ rhel8cis_pass['min_days'] }}"
        loop: "{{ rhel8cis_5_6_1_2_min_day_change.stdout_lines | default([]) }}"
        when:
            - rhel8cis_5_6_1_2_set_min_days_change

      - name: "5.6.1.2 | PATCH | Ensure minimum days between password changes is 7 or more | Warning"
        block:
            - name: "5.6.1.2 | PATCH | Ensure minimum days between password changes is 7 or more | Output list if not set to change"
              ansible.builtin.debug:
                  msg: |
                    "Warning!! The following account are set beyond the expected minimum days between passwords:
                     {{ rhel8cis_5_6_1_2_min_day_change.stdout_lines }}"

            - name: "5.6.1.2 | PATCH | Ensure minimum days between password changes is 7 or more | set warning fact"
              ansible.builtin.import_tasks: warning_facts.yml
              vars:
                  warn_control_id: '5.6.1.2'
        when:
            - rhel8cis_5_6_1_2_min_day_change is defined
            - rhel8cis_5_6_1_2_min_day_change.stdout | length > 0
            - not rhel8cis_5_6_1_2_set_min_days_change
  when:
      - rhel8cis_rule_5_6_1_2
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - password
      - rule_5.6.1.2

- name: "5.6.1.3 | PATCH | Ensure password expiration warning days is 7 or more"
  block:
      - name: "5.6.1.3 | AUDIT | Ensure password expiration warning days is 7 or more | capture accounts"
        ansible.builtin.shell: "grep -E '^[^:]+:[^!*]' /etc/shadow | awk -F':' '$4>{{ rhel8cis_pass['warn_age'] }} { print $1 }'"
        changed_when: false
        failed_when: rhel8cis_5_6_1_3_warn_age_change.rc not in [ 0, 1 ]
        register: rhel8cis_5_6_1_3_warn_age_change

      - name: "5.6.1.3 | PATCH | Ensure password expiration warning days is 7 or more | set default"
        ansible.builtin.lineinfile:
            path: /etc/login.defs
            regexp: '^PASS_WARN_AGE'
            line: "PASS_WARN_AGE {{ rhel8cis_pass['warn_age'] }}"

      - name: "5.6.1.3 | PATCH | Ensure password expiration warning days is 7 or more | Change users found"
        ansible.builtin.shell: "change --warndays {{ rhel8cis_pass['warn_age'] }} {{ item }}"
        loop: "{{ rhel8cis_5_6_1_3_warn_age_change.stdout_lines | default([]) }}"
        when:
            - rhel8cis_5_6_1_3_set_warn_age_change

      - name: "5.6.1.3 | PATCH | Ensure password expiration warning days is 7 or more | warning"
        block:
            - name: "5.6.1.3 | PATCH | Ensure password expiration warning days is 7 or more | Output list if not set to change"
              ansible.builtin.debug:
                  msg: |
                    "Warning!! The following account are set beyond the expected warning date:
                     {{ rhel8cis_5_6_1_3_warn_age_change.stdout_lines }}"

            - name: "5.6.1.3 | PATCH | Ensure password expiration warning days is 7 or more | set warning fact"
              ansible.builtin.import_tasks: warning_facts.yml
              vars:
                  warn_control_id: '5.6.1.3'
        when:
            - rhel8cis_5_6_1_3_warn_age_change is defined
            - rhel8cis_5_6_1_3_warn_age_change.stdout | length > 0
            - not rhel8cis_5_6_1_3_set_warn_age_change

  when:
      - rhel8cis_rule_5_6_1_3

  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - password
      - rule_5.6.1.3

- name: "5.6.1.4 | PATCH | Ensure inactive password lock is 30 days or less"
  block:
      - name: "5.6.1.4 | AUDIT | Ensure inactive password lock is 30 days or less | Getting user list"
        ansible.builtin.shell: "awk -F: '/^[^#:]+:[^\\!\\*:]*:[^:]*:[^:]*:[^:]*:[^:]*:(\\s*|-1|3[1-9]|[4-9][0-9]|[1-9][0-9][0-9]+):[^:]*:[^:]*\\s*$/ {print $1}' /etc/shadow"
        changed_when: false
        check_mode: false
        register: rhel_8_5_6_1_4_user_list

      - name: "5.6.1.4 | AUDIT | Ensure inactive password lock is 30 days or less | Check current settings"
        ansible.builtin.shell: useradd -D | grep INACTIVE={{ rhel8cis_inactivelock.lock_days }} | cut -f2 -d=
        changed_when: false
        failed_when: false
        check_mode: false
        register: rhel8cis_5_6_1_4_inactive_settings

      - name: "5.6.1.4 | PATCH | Ensure inactive password lock is 30 days or less | Set default inactive setting"
        ansible.builtin.shell: useradd -D -f {{ rhel8cis_inactivelock.lock_days }}
        when: rhel8cis_5_6_1_4_inactive_settings.stdout | length == 0

      - name: "5.6.1.4 | PATCH | Ensure inactive password lock is 30 days or less | Apply Inactive setting to existing accounts"
        ansible.builtin.shell: "chage --inactive {{ rhel8cis_inactivelock.lock_days }} {{ item }}"
        with_items:
            - "{{ rhel_8_5_6_1_4_user_list.stdout_lines }}"
  when:
      - rhel8cis_rule_5_6_1_4
  tags:
      - level1-server
      - level1-workstation
      - automated
      - patch
      - password
      - rule_5.6.1.4

- name: "5.6.1.5 | PATCH | Ensure all users last password change date is in the past"
  block:
      - name: "5.6.1.5 | AUDIT | Ensure all users last password change date is in the past | Get current date in Unix Time"
        ansible.builtin.shell: echo $(($(date --utc --date "$1" +%s)/86400))
        changed_when: false
        failed_when: false
        check_mode: false
        register: rhel8cis_5_6_1_5_currentut

      - name: "5.6.1.5 | AUDIT | Ensure all users last password change date is in the past | Get list of users with last changed pw date in the future"
        ansible.builtin.shell: "cat /etc/shadow | awk -F: '{if($3>{{ rhel8cis_5_6_1_5_currentut.stdout }})print$1}'"
        changed_when: false
        failed_when: false
        check_mode: false
        register: rhel8cis_5_6_1_5_user_list

      - name: "5.6.1.5 | AUDIT | Ensure all users last password change date is in the past | Alert no pw change in the future exist"
        ansible.builtin.debug:
            msg: "Good News! All accounts have PW change dates that are in the past"
        when: rhel8cis_5_6_1_5_user_list.stdout | length == 0

      - name: "5.6.1.5 | AUDIT | Ensure all users last password change date is in the past | Alert on accounts with pw change in the future"
        ansible.builtin.debug:
            msg: "Warning!! The following accounts have the last PW change date in the future: {{ rhel8cis_5_6_1_5_user_list.stdout_lines }}"
        when:
            - rhel8cis_5_6_1_5_user_list.stdout | length > 0
            - not rhel8cis_futurepwchgdate_autofix

      - name: "5.6.1.5 | AUDIT | Ensure all users last password change date is in the past| Warn Count"
        ansible.builtin.import_tasks: warning_facts.yml
        vars:
            warn_control_id: '5.6.1.5'
        when:
            - rhel8cis_5_6_1_5_user_list.stdout | length > 0
            - not rhel8cis_futurepwchgdate_autofix

      - name: "5.6.1.5 | PATCH | Ensure all users last password change date is in the past | Fix accounts with pw change in the future"
        ansible.builtin.shell: passwd --expire {{ item }}
        when:
            - rhel8cis_5_6_1_5_user_list | length > 0
            - rhel8cis_futurepwchgdate_autofix
        with_items:
            - "{{ rhel8cis_5_6_1_5_user_list.stdout_lines }}"
  when:
      - rhel8cis_rule_5_6_1_5
  tags:
      - level1-server
      - level1-workstation
      - patch
      - rule_5.6.1.5
